### ISSUE TITLE
the HUD color should be inverted when using black menu bar

### ISSUE THREAD

**Issue by drselump14** [w0lfschild/cleanHUD#1]
Thanks for making such a great plugin.

However, I think it would be better to automatically swap progresColor  and emptyColor when using black menu bar.
Current  progressColor is not visible when using black menubar.

Thanks

**Comment by drselump14** [comment]
Oh, sorry.. it's already implemented ... my bad

**Comment by w0lfschild** [comment]
Yeah I just haven't put the latest build on mySIMBL yet.
