### ISSUE TITLE
OSDUIHelper.app under Privacy>Automation

### ISSUE THREAD

**Issue by mikadocat** [w0lfschild/cleanHUD#10]
Hi, does cleanHUD require any other permission in addition to OSDUIHelper.app to function?

I seemed to have disabled something and cannot troubleshoot it.

Thanks!

![a](https://user-images.githubusercontent.com/46818052/63724284-af48bb00-c857-11e9-930d-4fd4a1e4b48b.png)

**Comment by w0lfschild** [comment]
cleanHUD shouldn't need you to make any changes in system preferences.

Maybe try using [MacForge](https://github.com/w0lfschild/MacForge) for plugin management/injection instead of mySIMBL.

**Comment by mikadocat** [comment]
Not working using MacForge either for me.

Using 0.6.2 bundle.
Uninstalled mySIMBL.
Installed MacForge.
SIP/AMFI disabled.

Other plugins work (NotificationClear, Afloat); but cleanHUD does not appear. 
It does disable the regular Apple HUD however.

**Comment by w0lfschild** [comment]
Is it possible you're experiencing this issue? https://github.com/w0lfschild/cleanHUD/issues/8

**Comment by mikadocat** [comment]
I use Bartender, but that wasn't ever an issue.

**Comment by w0lfschild** [comment]
What version of MacOS?

**Comment by mikadocat** [comment]
At the time I experienced it, 10.14.6

Have not tried on 10.15.x

**Comment by w0lfschild** [comment]
Put out a new version, I'm guessing it will fix your issue.
