### ISSUE TITLE
Not visible on Catalina

### ISSUE THREAD

**Issue by af97272** [w0lfschild/cleanHUD#11]
i am on OS 10.15.1, and cleanHUD isnt showing up, it works but there is no visual indicator. I am running cleanHUD version 0.7.2

**Comment by af97272** [comment]
MacForge also only picks up my AMFI disabled, but not my SIP which is  also disabled

**Comment by w0lfschild** [comment]
I'll just track any issues with the new HUD not showing here:

https://github.com/w0lfschild/cleanHUD/issues/9

Closing this for now.
