### ISSUE TITLE
cleanHUD not showing on macOS 10.15.3

### ISSUE THREAD

**Issue by dbonner** [w0lfschild/cleanHUD#12]
Hi, I bought cleanHUD and it shows as being installed in MacForge.  I have taken the advice on the System tab on MacForge (see screenshot).  There is nothing showing on my status bar.  Do I need to do anything else to activate it?
![Screen Shot 2020-02-01 at 10 01 50 pm](https://user-images.githubusercontent.com/241474/73591135-ffcaef80-453e-11ea-85cc-33589defbc44.png)

**Comment by w0lfschild** [comment]
Are you able to get other plugins loading?

**Comment by dbonner** [comment]
Yes,
AfloatX, binventory, cDock and colorfulSidebar9 work properly.
<img width="1536" alt="Screen Shot 2020-02-02 at 1 35 07 pm" src="https://user-images.githubusercontent.com/241474/73602052-0d28be00-45c1-11ea-9595-bee9537f7a8d.png">
As you can see there is no cleanHUD in the menu/status bar.

**Comment by w0lfschild** [comment]
Does it work if you restart Notification Center using Activity Monitor?

**Comment by dbonner** [comment]
No.  I tried quitting and also force quitting Notification Center.  It then
restarts as a new process.  Nothing is showing in the menu/status bar.

**Comment by w0lfschild** [comment]
@dbonner does this work?

[cleanHUD.bundle.zip](https://github.com/w0lfschild/cleanHUD/files/4222535/cleanHUD.bundle.zip)
