### ISSUE TITLE
Sharp edges and no shadow :/

### ISSUE THREAD

**Issue by hatake00** [w0lfschild/cleanHUD#13]
Hey,
sharp edges and no shadow makes it look ugly :/

<img width="354" alt="Zrzut ekranu 2020-08-8 o 19 16 42" src="https://user-images.githubusercontent.com/69398107/89716442-5a8d4a00-d9ad-11ea-93a0-bb74cfe629cf.png">
<img width="102" alt="Zrzut ekranu 2020-08-8 o 19 17 10" src="https://user-images.githubusercontent.com/69398107/89716444-5e20d100-d9ad-11ea-9874-4f1e3a11f571.png">

**Comment by w0lfschild** [comment]
I've added an option for window shadow with 0.11.4

As for the `corners` edges?, nothing I can really do about that.
