### ISSUE TITLE
When the background is black I don't know where is the bar

### ISSUE THREAD

**Issue by dortamiguel** [w0lfschild/cleanHUD#2]
Maybe a white transparent background for the progress bar should be fine

![image](https://cloud.githubusercontent.com/assets/3449006/25088303/4a0c7e7a-236d-11e7-8939-27478211cdb7.png)

**Comment by w0lfschild** [comment]
What version of cleanHUD are you using? This is how it looks in the latest version:

<img width="421" alt="screen shot 2017-04-23 at 2 22 41 pm" src="https://cloud.githubusercontent.com/assets/1920148/25317610/9e814c84-2830-11e7-874a-06aada0ec961.png">

Maybe it's an issue with dark mode not being detected. 
If you open terminal and type `defaults read NSGlobalDomain AppleInterfaceStyle` what do you get?

**Comment by dortamiguel** [comment]
I don't know what I did but now is working fine after a macos reinstall
