### ISSUE TITLE
When a key is not released the progress bar doesn't work

### ISSUE THREAD

**Issue by dortamiguel** [w0lfschild/cleanHUD#3]
If I maintain pressed down the bright or volume key the progress bar doesn't work as expected.

I'm on macos 10.12.4

**Comment by w0lfschild** [comment]
I'll look into this.

**Comment by dortamiguel** [comment]
It was the OS keyboard configuration, I deleted the keyboard delay between keys and works fine

**Comment by dstd** [comment]
@ellipticaldoor could you share your way to fix this? In my config the delay is shortest possible, but I still affected by the issue.

![keyboard 2018-08-28 18-18-43](https://user-images.githubusercontent.com/1444844/44732831-dc507980-aaee-11e8-9028-f4cc98eafb15.jpg)

**Comment by dortamiguel** [comment]
@dstd I have the same as you, try restarting and trying again

**Comment by dortamiguel** [comment]
Also you can try to run on your terminal

```
defaults write NSGlobalDomain KeyRepeat -int 0
```
