### ISSUE TITLE
Update for dark mode?

### ISSUE THREAD

**Issue by Ipeleng** [w0lfschild/cleanHUD#4]
Having the bar white and the menu dark breaks the 'cleanness' of the whole look. Great tweak btw

**Comment by w0lfschild** [comment]
So a semi transparent white background?

**Comment by samaero** [comment]
I love this tweak - thank you!

I don't know how to code, or else I would have done this more elegantly, but I hacked this together by swapping the dark mode / light modes and reducing the Background Color Alpha values to 0.0. The "empty" portion of the volume slider is now pretty hard to see against the dark menu bar (maybe a thin white outline around the empty portion, Itsycal style, would fix this?), but overall I think it sits better with Mac OS' dark mode.

<img width="847" alt="screen shot 2017-04-25 at 11 47 58 pm" src="https://cloud.githubusercontent.com/assets/27949579/25421729/fe3494c2-2a12-11e7-9f47-6983893a7f45.png">

**Comment by Ipeleng** [comment]
Samaeo got it just perfect basically what i mean.

**Comment by Ipeleng** [comment]
Samaeo Could you explain how you did it?

**Comment by samaero** [comment]
Ipeleng I can check the specific lines I modified later, but there's a point in the code in which cleanHUD checks if it's in Dark Mode or not; this determines whether it's going to use the black text & images (Dark Mode) or the white text & images (Regular Mode). First, I switched those values so that it uses the white assets when in dark mode, and vice versa. Then, I edited the alpha values for both the Dark and Regular mode backgrounds (which control the transparency) to make them fully transparent (0.0), effectively hiding them.

**Comment by themightykitten** [comment]
I was about to post an issue for the exact same thing! :)

**Comment by w0lfschild** [comment]
Hmm yeah this is possible.

**Comment by Ipeleng** [comment]
samaero I've tried to find a way to edit the code but I have no idea how to open it. the furthest I've gotten is the executable inside the Show contents. Would i have to open it in xcode?

**Comment by samaero** [comment]
@Ipeleng I opened a pull request for the change. If you want to re-create it locally, yeah, you'll have to open it in Xcode, make the changes listed in the pull request, and re-build it.

**Comment by Ipeleng** [comment]
@samaero Do I drag the cleanHub.bundle into xcode or the package contents

**Comment by samaero** [comment]
@Ipeleng you'd need to download the full source code as a zip, open the cleanHUD.xcodeproj file in Xcode, make the changes, and then build the plugin.

Alternately, you can just download/install the modified bundle from my pull request fork:
https://github.com/samaero/cleanHUD/tree/master/build

**Comment by unknown--** [comment]
@samaero 

Offtopic: What is the menu item you're using to display the date and battery level? They look quite nice.

**Comment by samaero** [comment]
@unknown-- the Date/Time display is Itsycal, and it's actually a really handy little calendar. The battery is SlimBatteryMonitor - it's older and a little clunky, but I haven't found a better replacement.

**Comment by sidpagariya** [comment]
@w0lfschild Is there a possibility to completely remove the light overlay that you have (the white rectangle over which the volume control is placed)? That would look quite elegant and it would be really simple looking, too!

**Comment by w0lfschild** [comment]
Okay version 0.5.2 now uses a style pretty similar to this.
