### ISSUE TITLE
Colors of HUD are inversed in macOS 10.13 High Sierra

### ISSUE THREAD

**Issue by Fofer** [w0lfschild/cleanHUD#6]
I just updated to High Sierra and now notice that cleanHUD looks different; with colors that are inversed. They have have a dark black background with white elements.  (It no longer has that nice translucency that blended into the menubar.)  And cleanHUD is the only element that looks different.  (I have not enabled Dark mode.)

**Comment by w0lfschild** [comment]
Yeah I think I need to roll out a fix for High Sierra. It'll happen eventually.

Should be fixed in 0.5.2
