### ISSUE TITLE
Edges of indicator bar appear soft/faded

### ISSUE THREAD

**Issue by qwertimus** [w0lfschild/cleanHUD#7]
Hi, I'm running a clean install of Sierra (10.12.6 + security updates) with mySIMBL (0.5.3) and CleanHUD (0.5.2). As described in the title (and shown below), the edges of indicator bar appear soft/faded, especially compared to the 'filled' bar edges. This was not the case on my previous system, ElCap with CleanHUD 0.4.3.

Is this intentional, or is this a result of adding Dark Mode support?

<img width="320" alt="screen shot 2018-01-03 at 8 25 07 pm" src="https://user-images.githubusercontent.com/1412513/34515044-749e0530-f0c4-11e7-8ac7-81ce631b426b.png">

Edit: The indicator bar edges appear the same (faded) in both Dark & Light mode.

**Comment by qwertimus** [comment]
Another side effect of removing the background is the indicator bar becomes difficult to read in certain situations.
I will downgrade to cleanHUD (0.4.3) for the moment.

<img width="320" alt="screen shot 2018-01-03 at 9 02 16 pm" src="https://user-images.githubusercontent.com/1412513/34516162-f061bef0-f0c9-11e7-9094-b3a32160aafa.png">

**Comment by w0lfschild** [comment]
Yeah I was having difficulty figuring out how to give the hud a NSVisualEffectView that was active as a background process but it was actually really easy: 

`[indiBlur setState:NSVisualEffectStateActive];`

I've also fixed the background being 2 pixels too short which was causing the first issue.

Should have 0.5.3 up on mySIMBL tomorrow.

**Comment by w0lfschild** [comment]
Update should be out now.

- Requires macOS 10.10+
- Fix overlapping text with blurred background so it's readable but still blends with background
- Fix misalignment of indicator and background by 2px
- Fix for issue where it would determine the wrong color if both loginwindow and OSDUIHelper were trying to show the HUD at the same time

**Comment by qwertimus** [comment]
Thank you, 0.5.3 is awesome! Very elegant solution!
