### ISSUE TITLE
I have issues with CleanHUD overlay other statusbar app

### ISSUE THREAD

**Issue by lilws** [w0lfschild/cleanHUD#8]
Recently I use Vanilla from matthewpalmer. Here is his website https://matthewpalmer.net/vanilla/

This app help hiding the statusbar icon so it will look clear. But the problem is when it hides the icon, it also hides the HUD too. So there is overlay problem here. I wonder if you can fix this or make an option allow to move the HUD to some where else on the bar.

Here is the video
[cleanHUD overlay.mov.zip](https://github.com/w0lfschild/cleanHUD/files/2215780/cleanHUD.overlay.mov.zip)

**Comment by mikadocat** [comment]
I use Bartender, similar to Vanilla, but it works fine for me, i.e. it's not hidden like @lilws 
However, with or without it, the HUD does not match the height of the status bar.
This is on HS 10.13.

<img width="1050" alt="screen shot 2019-02-20 at 14 41 47" src="https://user-images.githubusercontent.com/46818052/53096366-45a1ca00-351f-11e9-8f9f-c1c23139cb52.png">

**Comment by w0lfschild** [comment]
Fixed in https://github.com/w0lfschild/cleanHUD/commit/96fbfe0c77bfee95f05229fc9fce73b71d02a024
