### ISSUE TITLE
Not visible

### ISSUE THREAD

**Issue by StivMs** [w0lfschild/cleanHUD#9]
I tried installing the plugin by dragging it to the MySimbl and also installing it via the tool itself but I don't see any volume-bar after installing it.

**Comment by erenakbltt** [comment]
I have same issue on 10.14.2

**Comment by w0lfschild** [comment]
It needs to be updated.

**Comment by w0lfschild** [comment]
[0.6.1](https://github.com/w0lfschild/cleanHUD/commit/89381b5ddeb8ce5e917cd306d2fce9f1e9ac51cb) works. You'll have to build from source or you can buy it in [MacForge](https://github.com/w0lfschild/MacForge).

**Comment by Tizioincognit0** [comment]
The last build is for 0.5.3: https://github.com/w0lfschild/cleanHUD/tree/master/build.

**Comment by w0lfschild** [comment]
@Tizioincognit0 

Which is why I said you'll have to either build it from source yourself (now up to 0.6.2) using Xcode or buy it in [MacForge](https://github.com/w0lfschild/MacForge).

**Comment by stevieis404** [comment]
Hi, I recently bought the plugin (0.6.1) in MacForge but still have the problem, is it not compatible w 10.14.6 ?

**Comment by w0lfschild** [comment]
Well I'll look into it. Maybe for some reason the 10.14 HUD implementation was changed but the 10.15 wasn't?

It definitely works on 10.15

**Comment by stevieis404** [comment]
Thanks! Could also be bc I use Bartender (menu bar app problem like your other thread), but it still happens when I quit the app so idk...

**Comment by af97272** [comment]
i am on OS 10.15.1, and cleanHUD isnt showing up, it works but there is no visual indicator. I am running cleanHUD version 0.7.2

**Comment by Tizioincognit0** [comment]
> i am on OS 10.15.1, and cleanHUD isnt showing up, it works but there is no visual indicator. I am running cleanHUD version 0.7.2

I have the same issue but on macOS 10.14.6.

**Comment by w0lfschild** [comment]
@af97272 @Tizioincognit0 

Are either of you able to get other plugins to load?

Do you have AMFI on or off? It requires a reboot to apply changes.

**Comment by af97272** [comment]
@w0lfschild  

I have 100% turned off SIP, with AMFI, I searched up how to turn it off and in recovery terminal i used the command:
nvram boot-args="amfi_get_out_of_my_way=0x1" 

Nothing showed up so I decided to reboot and check, but in MacForge AMFI had at tick, but my SIP was still unchecked even though it was already disabled.

**Comment by w0lfschild** [comment]
The check mark means it's enabled, not disabled.
- [X] Enabled
- [ ] Disabled

You want both the SIP and AMFI check boxes to be unchecked.

Are you able to get other plugins loaded?

The HUD element is drawn by SystemUIServer which now that I'm checking does have hardened runtime so will require AMFI to be off.

You can toggle AMFI by clicking the check box in MacForge and then rebooting.

**Comment by af97272** [comment]
When I first installed MacForge, it was already off but the cleanHUD change was working, but not visible.

I will try it again and uncheck AMFI, but I think I have already done so without it working.

Yes I also use binventory and it works perfectly fine

**Comment by w0lfschild** [comment]
@af97272 

Upon doing some testing it seems like `nvram boot-args="amfi_get_out_of_my_way=1"` can only be set if SIP is off or the flag `--without NVRAM` has been used. Not sure if this is a recent change or not.

Not sure if it can be set in recovery mode or not yet.

Updates for MacForge will be coming soon to hopefully clarify this and also info will be added to the System tab hopefully showing more detailed status.

**Comment by af97272** [comment]
So does this mean that, at the moment it just wont work for me?

**Comment by w0lfschild** [comment]
I mean it will show the HUD if you turn off AMFI. The update for MacForge isn't going to be able to do that for you.

I'm probably just gonna put out an update for cleanHUD at some point here that switches to using the CoreServicesUIAgent to draw the custom hud because that doesn't seem to have a hardened runtime (yet).

**Comment by w0lfschild** [comment]
Okay two things

* Turns out SIP must be completely off, will not work with partial disabled.
* AMFI can be changed in the recovery terminal

**Comment by w0lfschild** [comment]
@af97272 

Try updating to cleanHUD 0.7.3 and see if it works for you.

**Comment by samaero** [comment]
0.7.3 working again for me on Mojave 10.14.6 (with SIP and AMFI both completely disabled via recovery mode terminal)!

**Comment by w0lfschild** [comment]
@samaero 

That's great!

Didn't mention it in the last note but 0.7.3 should also work with AMFI enabled and with SIP partially enabled. As it's now using NotificationCenter to draw the HUD which is not protected with Library Validation (AMFI).

**Comment by af97272** [comment]
@w0lfschild 

Hi! Sorry for the late response,

But how do I turn off SIP completely, isnt it already completely off if I deactivate it through recovery mode terminal? And how exactly would I change AMFI in the recovery terminal?

**Comment by w0lfschild** [comment]
With cleanHUD 0.7.3 you shouldn't need to turn AMFI off.

To disable SIP the command is : `csrutil disable`
To disable AMFI the command is : `nvram boot-args="amfi_get_out_of_my_way=1"`

**Comment by af97272** [comment]
I have updated cleanHUD to version 0.7.3, and AMFI and SIP are both off but it isn't working, I restarted my laptop but it still wasn't working.

<img width="361" alt="Screen Shot 2019-11-29 at 1 47 45 pm" src="https://user-images.githubusercontent.com/58166049/69840217-d4155a00-12ae-11ea-9703-1788193d4646.png">
<img width="244" alt="Screen Shot 2019-11-29 at 1 47 39 pm" src="https://user-images.githubusercontent.com/58166049/69840222-daa3d180-12ae-11ea-9c70-e951532deb69.png">

Should I restart in Recovery OS and re-enable both and then disable them?

**Comment by w0lfschild** [comment]
Did MacForge ask for your password? The helper can't do anything without the injector installed.

**Comment by w0lfschild** [comment]
Are you seeing crashes here?

~/Library/Logs/DiagnosticReports/

**Comment by af97272** [comment]
Yes it has asked for a password, and I have approved it

Here is a screenshot in the folder.
<img width="571" alt="Screen Shot 2019-11-29 at 11 11 26 pm" src="https://user-images.githubusercontent.com/58166049/69868371-a0adec00-12fd-11ea-8021-9e3406c82045.png">

**Comment by w0lfschild** [comment]
Can you zip those up and upload them?

Looks like the helper is crashing for you. Have you updated MacFroge to 0.13.2?

**Comment by af97272** [comment]
Here are the files:
[Archive.zip](https://github.com/w0lfschild/cleanHUD/files/3906966/Archive.zip)

Yes MacForge is on version 0.13.2

**Comment by samaero** [comment]
Wanted to reply and confirm that CleanHUD 0.7.3 w/ MacForge 0.13.2 is still working for me on Mojave 10.14.6 with AMFI re-enabled and SIP partially enabled with the following two terminal commands:

csrutil enable --without fs --without debug
nvram boot-args="amfi_get_out_of_my_way=0x0"

Thanks!
